apiVersion: v1
kind: Service
metadata:
  name: nodeweb-service  # Service 的名称
  namespace: node-web
spec:
  selector:
    app: nodeweb-deployment    # 选择器匹配你要暴露的 Pod
  ports:
    - protocol: TCP
      nodePort: 32000 
      port: 3000      # Service 公开的端口
      targetPort: 3000  # Pod 上运行的容器端口
  type: NodePort
